name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compilar-y-desplegar.yml'
      - 'GithubActionsDemoApp/**'
      - 'Pruebas/**'
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-lates
    permissions:
      contents: write
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3.4.2
        with: 
          dotnet-version: 8.0.x

      - name: Obteneindo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar pruebas
        run: dotnet test --no-build

      - name: dotnet publish
        run: dotnet publish $proyecto -c Release -o miapp --runtime win-x86

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./miapp
          name: build

      - name: Zip
        if: starstsWith(github.ref, 'refs/tags')
        run: zip -r mi_app.zip ./miapp

      - name: GH Release
        if: starstsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: ./mi_app.zip
          body: "Nuestra aplicacion"
          tag_name: ${{ github.ref_name }}
