name: Compilar y desplegar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3.4.2
        with: 
          dotnet-version: 8.0.x

      - name: Obteneindo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore
