name: Compilar y probar

on:
  pull_request:
    branches: 
      - main


env: 
  VERSION_DOTNET: '8'

jobs:
  build:
    runs-on: ubuntu-lates
    permissions:
      contents: write
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3.4.2
        with: 
          dotnet-version: ${{env.VERSION_DOTNET}}


      - name: Obteneindo las dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Realizar pruebas
        run: dotnet test --no-build

